# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'centos64_64min'
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
  config.vm.forward_port 80, 80
  config.vm.forward_port 443, 443
  config.vm.forward_port 53, 53
  config.vm.forward_port 8080, 8080
  config.vm.forward_port 8118, 8118

  config.vm.host_name = 'broker.example.com'
  
  config.vm.share_folder "manifests", "/home/vagrant/manifests", "manifests"
  config.vm.provision :shell, :inline => %{ \
    touch /var/log/origin-setup.log; \
    sudo yum update -y                                          | tee -a /var/log/origin-setup.log; \
    sudo puppet module uninstall openshift/openshift_origin          | tee -a /var/log/origin-setup.log; \
    sudo puppet module install openshift/openshift_origin            | tee -a /var/log/origin-setup.log; \
    sudo puppet apply --verbose /home/vagrant/manifests/init.pp      | tee -a /var/log/origin-setup.log; \
    sudo puppet apply --verbose /home/vagrant/manifests/configure.pp | tee -a /var/log/origin-setup.log; \
  
    sudo /etc/init.d/network  restart               | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/activemq restart               | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/cgconfig restart               | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/cgred restart                  | tee -a /var/log/origin-setup.log; \
    sleep 5; \
    sudo /etc/init.d/openshift-cgroups restart      | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/httpd restart                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/openshift-broker restart       | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/openshift-node-web-proxy restart  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/named restart                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/mcollective restart            | tee -a /var/log/origin-setup.log; \
    sudo /usr/sbin/oo-register-dns -h broker -n 127.0.0.1       | tee -a /var/log/origin-setup.log;
  }
end
