# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'centos64_64min'
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
  config.vm.forward_port 80, 80
  config.vm.forward_port 443, 443
  config.vm.forward_port 53, 53
  config.vm.forward_port 8080, 8080
  config.vm.forward_port 8118, 8118

  config.vm.host_name = 'broker.example.com'

  ############## Use this with this plugin : https://github.com/dotless-de/vagrant-vbguest
  # It aims to rebuild VBox additions (drivers, shared folder, mouse integration, etc.)
  # when kernel or VBox have been updated
  Vagrant::Config.run do |config|
    # we will try to autodetect this path. 
    # However, if we cannot or you have a special one you may pass it like:
    # config.vbguest.iso_path = "#{ENV['HOME']}/Downloads/VBoxGuestAdditions.iso"
    # or
    # config.vbguest.iso_path = "http://company.server/VirtualBox/%{version}/VBoxGuestAdditions.iso"
    # set auto_update to false, if do NOT want to check the correct additions 
    # version when booting this machine
    config.vbguest.auto_update = true
    # do NOT download the iso file from a webserver
    config.vbguest.no_remote = true
  end
  ##############################
  
  config.vm.share_folder "manifests", "/home/vagrant/manifests", "manifests"
  config.vm.provision :shell, :inline => %{ \
    touch /var/log/origin-setup.log; \
	sudo rpm -ivh http://ftp-stud.hs-esslingen.de/pub/epel/6/i386/epel-release-6-8.noarch.rpm          | tee -a /var/log/origin-setup.log; \
    sudo yum update -y                                                                                 | tee -a /var/log/origin-setup.log; \
    sudo rpm -ivh http://yum.puppetlabs.com/el/6/products/i386/puppetlabs-release-6-6.noarch.rpm       | tee -a /var/log/origin-setup.log; \
    sudo yum install -y puppet facter                                                                  | tee -a /var/log/origin-setup.log; \
    sudo rpm -e $(rpm -qa | grep -i puppetlabs-release)                                                | tee -a /var/log/origin-setup.log; \
    sudo puppet module install puppetlabs/stdlib                                                       | tee -a /var/log/origin-setup.log; \
    sudo puppet module install puppetlabs/ntp                                                          | tee -a /var/log/origin-setup.log; \
    sudo yum update -y                                                                                 | tee -a /var/log/origin-setup.log; \
    sudo puppet module uninstall openshift/openshift_origin                                            | tee -a /var/log/origin-setup.log; \
    sudo puppet module install openshift/openshift_origin                                              | tee -a /var/log/origin-setup.log; \
    sudo puppet apply --verbose /home/vagrant/manifests/init.pp                                        | tee -a /var/log/origin-setup.log; \
    sudo puppet apply --verbose /home/vagrant/manifests/configure.pp                                   | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/network  restart                                                                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/activemq restart                                                                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/cgconfig restart                                                                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/cgred restart                                                                     | tee -a /var/log/origin-setup.log; \
    sleep 5; \
    sudo /etc/init.d/openshift-cgroups restart                                                         | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/httpd restart                                                                     | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/openshift-broker restart                                                          | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/openshift-node-web-proxy restart                                                  | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/named restart                                                                     | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/mcollective restart                                                               | tee -a /var/log/origin-setup.log; \
	sudo sed -i 's/SELINUX=disabled/SELINUX=permissive/g' /etc/selinux/config                          | tee -a /var/log/origin-setup.log; \
	sudo sed -i 's/nameserver .*$/nameserver 127.0.0.1/g' /etc/resolv.conf                             | tee -a /var/log/origin-setup.log; \
	sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config        | tee -a /var/log/origin-setup.log; \
    sudo /etc/init.d/sshd restart                                                                      | tee -a /var/log/origin-setup.log; \
    sudo /usr/sbin/oo-register-dns -h broker -n 127.0.0.1                                              | tee -a /var/log/origin-setup.log;
  }
end
